gText_Birch_Welcome::
	.string "Benvenuto giovane avventuriero \p"
	.string "Benvenuto nel mondo dei Pokimons \p"
	.string "Il mio è... va bhè già lo saprai... \p"
	.string "Ma tutti mi chiamano il \n"
	.string "Pokimons lover. \p"
	.string "Guarda cosa ho cagato oggi,\n"
	.string "ha fatto molto male \p"
	.string "$"

gText_Birch_Pokemon::
	.string "Te lo sto a fa vedè perchè \p"
	.string "assomigia molto, \n"
	.string "ma non lo è, ad un Pokimon \p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Qualche anno fa un folle scienziato\n"
	.string "Cof Cof, il negro, Cof Cof.\p"
	.string "Ha provato, senza le dovute conoscienze,\n"
	.string "a modificare geneticamente un topo\p"
	.string "ed ora sti abomini che per qualche \n"
	.string "ragione so tutti froci, escono da\p"
	.string "LE FOTTUTE PARETI\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl:: 
    .string "$"

gText_Birch_WhatsYourName::
	.string "Senti.\n"
	.string "Come te intitoli?$"

gText_Birch_SoItsPlayer::
	.string "Quindi è Philipps?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "Vabbe mo sbrigamose che ciò da fa\n"
	.string "mi ha scritto una su instagram\l"
	.string "è sicuramente matta...\p"
	.string "Movemose che ciò da fà, le bimbe...\p"
	.string "$"

gText_Birch_AreYouReady::
    .string "$"
